apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-management-app.backend.fullname" . }}
  namespace: {{ .Values.backend.namespace }}
  labels:
    {{- include "user-management-app.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-management-app.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-management-app.backend.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "user-management-app.backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            - name: FLASK_ENV
              value: {{ .Values.backend.env.flaskEnv }}
            {{- with .Values.backend.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.healthCheck.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.backend.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.healthCheck.failureThreshold }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}