apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-management-app.frontend.fullname" . }}
  namespace: {{ .Values.frontend.namespace }}
  labels:
    {{- include "user-management-app.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-management-app.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-management-app.frontend.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "user-management-app.frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: "http://{{ include "user-management-app.backend.fullname" . }}.{{ .Values.backend.namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/api"
            {{- with .Values.frontend.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.healthCheck.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.healthCheck.failureThreshold }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}